CREATE TABLE IF NOT EXISTS RMSData (
    [Department]                      TEXT NOT NULL,
    [Team]                            TEXT,
    [Employee Name]                   TEXT NOT NULL,
    [Jan Project Work]                INTEGER DEFAULT 0,
    [Jan Departmental Internal Work]  INTEGER DEFAULT 0,
    [Jan Vacation]                    INTEGER DEFAULT 0,
    [Jan Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Jan Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Feb Project Work]                INTEGER DEFAULT 0,
    [Feb Departmental Internal Work]  INTEGER DEFAULT 0,
    [Feb Vacation]                    INTEGER DEFAULT 0,
    [Feb Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Feb Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Mar Project Work]                INTEGER DEFAULT 0,
    [Mar Departmental Internal Work]  INTEGER DEFAULT 0,
    [Mar Vacation]                    INTEGER DEFAULT 0,
    [Mar Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Mar Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Apr Project Work]                INTEGER DEFAULT 0,
    [Apr Departmental Internal Work]  INTEGER DEFAULT 0,
    [Apr Vacation]                    INTEGER DEFAULT 0,
    [Apr Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Apr Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [May Project Work]                INTEGER DEFAULT 0,
    [May Departmental Internal Work]  INTEGER DEFAULT 0,
    [May Vacation]                    INTEGER DEFAULT 0,
    [May Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [May Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Jun Project Work]                INTEGER DEFAULT 0,
    [Jun Departmental Internal Work]  INTEGER DEFAULT 0,
    [Jun Vacation]                    INTEGER DEFAULT 0,
    [Jun Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Jun Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Jul Project Work]                INTEGER DEFAULT 0,
    [Jul Departmental Internal Work]  INTEGER DEFAULT 0,
    [Jul Vacation]                    INTEGER DEFAULT 0,
    [Jul Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Jul Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Aug Project Work]                INTEGER DEFAULT 0,
    [Aug Departmental Internal Work]  INTEGER DEFAULT 0,
    [Aug Vacation]                    INTEGER DEFAULT 0,
    [Aug Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Aug Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Sep Project Work]                INTEGER DEFAULT 0,
    [Sep Departmental Internal Work]  INTEGER DEFAULT 0,
    [Sep Vacation]                    INTEGER DEFAULT 0,
    [Sep Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Sep Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Oct Project Work]                INTEGER DEFAULT 0,
    [Oct Departmental Internal Work]  INTEGER DEFAULT 0,
    [Oct Vacation]                    INTEGER DEFAULT 0,
    [Oct Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Oct Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Nov Project Work]                INTEGER DEFAULT 0,
    [Nov Departmental Internal Work]  INTEGER DEFAULT 0,
    [Nov Vacation]                    INTEGER DEFAULT 0,
    [Nov Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Nov Available Bandwidth (%)]     INTEGER DEFAULT 0,
    [Dec Project Work]                INTEGER DEFAULT 0,
    [Dec Departmental Internal Work]  INTEGER DEFAULT 0,
    [Dec Vacation]                    INTEGER DEFAULT 0,
    [Dec Available Bandwidth (PD)]    INTEGER DEFAULT 0,
    [Dec Available Bandwidth (%)]     INTEGER DEFAULT 0,

    PRIMARY KEY (Department, [Employee Name])

);
