INSERT INTO RMSData (
    [Department],
    [Team],
    [Employee Name],
    [Jan Available Bandwidth (PD)],
    [Feb Available Bandwidth (PD)],
    [Mar Available Bandwidth (PD)],
    [Apr Available Bandwidth (PD)],
    [May Available Bandwidth (PD)],
    [Jun Available Bandwidth (PD)],
    [Jul Available Bandwidth (PD)],
    [Aug Available Bandwidth (PD)],
    [Sep Available Bandwidth (PD)],
    [Oct Available Bandwidth (PD)],
    [Nov Available Bandwidth (PD)],
    [Dec Available Bandwidth (PD)],
    [Jan Available Bandwidth (%)],
    [Feb Available Bandwidth (%)],
    [Mar Available Bandwidth (%)],
    [Apr Available Bandwidth (%)],
    [May Available Bandwidth (%)],
    [Jun Available Bandwidth (%)],
    [Jul Available Bandwidth (%)],
    [Aug Available Bandwidth (%)],
    [Sep Available Bandwidth (%)],
    [Oct Available Bandwidth (%)],
    [Nov Available Bandwidth (%)],
    [Dec Available Bandwidth (%)] )
VALUES
(?,?,?,
?,?,?,
?,?,?,
?,?,?,
?,?,?,
?,?,?,
?,?,?,
?,?,?,
?,?,?);